spring.application.name=backend

# DB
spring.datasource.url=${postgresql://postgres:[Shivang@1432]@db.rgsqjpnsqlsaowxzqlzi.supabase.co:5432/postgres}
spring.datasource.username=${postgres}
spring.datasource.password=${Shivang@1432}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=${smtp.gmail.com}
spring.mail.port=${587}
spring.mail.username=${ultronthor037@gmail.com}
spring.mail.password=${fuuj adbe wozd wbce}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${8fK3!xP9@vQ2#Lm7$Zr6&Nd1*Ht5YwU4Bs0GkJcR}

# Admin
admin.email=${shivangv493@gmail.com}

server.port=${PORT:8080}



