spring.application.name=backend

# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://db.rgsqjpnsqlsaowxzqlzi.supabase.co:5432/postgres?prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Shivang@1432}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ultronthor037@gmail.com
spring.mail.password=fuuj adbe wozd wbce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=8fK3!xP9@vQ2#Lm7$Zr6&Nd1*Ht5YwU4Bs0GkJcR
jwt.expiration=86400000

# Admin
admin.email=shivangv493@gmail.com

server.port=${PORT:8080}
